### ISSUE TITLE
analysis with KVIVSelector doesn't work

### ISSUE THREAD

**Issue by jdfrankland** [kaliveda-dev/kaliveda#49]
```
#5  0x000000000c7b78a8 in ?? ()
#6  0x00007f78cdef2577 in int TStreamerInfo::ReadBuffer<char**>(TBuffer&, char** const&, TStreamerInfo::TCompInfo* const*, int, int, int, int, int) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#7  0x00007f78cdde84dd in TStreamerInfoActions::GenericReadAction(TBuffer&, void*, TStreamerInfoActions::TConfiguration const*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#8  0x00007f78cdda0135 in TBufferFile::ApplySequence(TStreamerInfoActions::TActionSequence const&, void*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#9  0x00007f78cdd9edfb in TBufferFile::ReadClassBuffer(TClass const*, void*, TClass const*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#10 0x00007f78d071d250 in TClonesArray::Streamer(TBuffer&) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libCore.so
#11 0x00007f78cdda1051 in TBufferFile::ReadFastArray(void**, TClass const*, int, bool, TMemberStreamer*, TClass const*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#12 0x00007f78cdef24c6 in int TStreamerInfo::ReadBuffer<char**>(TBuffer&, char** const&, TStreamerInfo::TCompInfo* const*, int, int, int, int, int) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#13 0x00007f78cdde84dd in TStreamerInfoActions::GenericReadAction(TBuffer&, void*, TStreamerInfoActions::TConfiguration const*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#14 0x00007f78cdda0135 in TBufferFile::ApplySequence(TStreamerInfoActions::TActionSequence const&, void*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#15 0x00007f78cdd9edfb in TBufferFile::ReadClassBuffer(TClass const*, void*, TClass const*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#16 0x00007f78d0764e38 in TStreamerBase::ReadBuffer(TBuffer&, char*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libCore.so
#17 0x00007f78cdef26b7 in int TStreamerInfo::ReadBuffer<char**>(TBuffer&, char** const&, TStreamerInfo::TCompInfo* const*, int, int, int, int, int) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#18 0x00007f78cdde84dd in TStreamerInfoActions::GenericReadAction(TBuffer&, void*, TStreamerInfoActions::TConfiguration const*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#19 0x00007f78cdda0135 in TBufferFile::ApplySequence(TStreamerInfoActions::TActionSequence const&, void*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#20 0x00007f78cdd9edfb in TBufferFile::ReadClassBuffer(TClass const*, void*, TClass const*) () from /home/fable/software/install/.root-6.07_gcc-4.8.4_x86_64/lib/libRIO.so
#21 0x00007f78cbe15fe1 in KVReconstructedEvent::Streamer (this=0x686adb0/build/buildd/gdb-7.7.1/gdb/stack.c:612: internal-error: print_frame_args: Assertion `nsym != NULL' failed.
===========================================================
```

**Comment by FableQuentin** [comment]
Using ROOT 6.07/02 and KaliVeda version 1.10/14

Trying to apply a KVIVSelector inherited class on "recon" and also "ident" data. Concerning recon runs, I have tried the last generated (09 march 2017) runs at CC for 48Ca+48Ca system.

**Comment by jdfrankland** [comment]
Avec ROOT 6.09/01 (même version qu'au centre) pas de problème pour run recon 379
Soit il faut pas utiliser 6.07/02 soit le fichier en question est pourri?
Tu as essayé au centre?

**Comment by FableQuentin** [comment]
J'ai refait la même chose avec ROOT 5.34 et tout marche...
Pareil au CC ça fonctionne ...

je comprends pô lô ...

**Comment by jdfrankland** [comment]
je te conseille d'utiliser la branche "master" de ROOT (=>6.09/01)
ou sinon de rester en 5.34
:)
