### ISSUE TITLE
segfault on delete gMultiDetArray with ROOTv6.12/07

### ISSUE THREAD

**Issue by jdfrankland** [kaliveda-dev/kaliveda#74]
seen with latest version of 6.12 & also master branches
does not occur with versions 5.34,6.08,6.10

building MDA OK, but deleting it (i.e. if you try to build a different MDA) ends in:

#5  0x00007f8b182c1170 in vtable for std::_Sp_counted_ptr_inplace<TObjLink, std::allocator<TObjLink>, (__gnu_cxx::_Lock_policy)2> () from /home/frankland/software/install/root-v6-12-00/lib/libCore.so.6.12
#6  0x00007f8b17f4889d in TList::FindObject (this=<optimized out>, obj=0x7ef7500) at /home/frankland/software/sources/root/core/cont/src/TList.cxx:614
#7  0x00007f8b17f4618d in THashList::RecursiveRemove (this=0x5c83c30, obj=0x7ef7500) at /home/frankland/software/sources/root/core/cont/src/THashList.cxx:328
#8  0x00007f8b17f45f93 in THashList::RecursiveRemove (this=<optimized out>, obj=0x7ef7500) at /home/frankland/software/sources/root/core/cont/src/THashList.cxx:354
#9  0x00007f8b17f45f93 in THashList::RecursiveRemove (this=<optimized out>, obj=0x7ef7500) at /home/frankland/software/sources/root/core/cont/src/THashList.cxx:354
#10 0x00007f8b17e3c313 in TROOT::RecursiveRemove (this=0x7f8b182d8e00 <ROOT::Internal::GetROOT1()::alloc>, obj=<optimized out>) at /home/frankland/software/sources/root/core/base/src/TROOT.cxx:2440
#11 0x00007f8b17ee5272 in CallRecursiveRemoveIfNeeded (obj=...) at /home/frankland/software/build/root/build-v6-12-00-patches/include/TROOT.h:387
#12 TNamed::~TNamed (this=0x7ef7500, __in_chrg=<optimized out>) at /home/frankland/software/sources/root/core/base/src/TNamed.cxx:45
#13 0x00007f8b1a4f3217 in ~KVACQParam (this=0x7ef7500, __in_chrg=<optimized out>) at /home/frankland/software/sources/kaliveda.git/KVMultiDet/geometry/KVACQParam.h:45
#14 KVACQParam::~KVACQParam (this=0x7ef7500, __in_chrg=<optimized out>) at /home/frankland/software/sources/kaliveda.git/KVMultiDet/geometry/KVACQParam.h:46
#15 0x00007f8b17f4d41f in TList::Delete (this=0x7ae5140, option=<optimized out>) at /home/frankland/software/sources/root/core/cont/src/TList.cxx:534
#16 0x00007f8b17f4cb22 in TList::Clear (this=0x7ae5140, option=<optimized out>) at /home/frankland/software/sources/root/core/cont/src/TList.cxx:407
#17 0x00007f8b17f4cf51 in TList::~TList (this=0x7ae5140, __in_chrg=<optimized out>) at /home/frankland/software/sources/root/core/cont/src/TList.cxx:91
#18 0x00007f8b17f4d0d9 in TList::~TList (this=0x7ae5140, __in_chrg=<optimized out>) at /home/frankland/software/sources/root/core/cont/src/TList.cxx:92
#19 0x00007f8b18ddcc9c in KVSeqCollection::~KVSeqCollection (this=0x7ef73f0, __in_chrg=<optimized out>) at /home/frankland/software/sources/kaliveda.git/KVMultiDet/base/KVSeqCollection.cpp:187
#20 0x00007f8b18dcc8e9 in KVList::~KVList (this=0x7ef73f0, __in_chrg=<optimized out>) at /home/frankland/software/sources/kaliveda.git/KVMultiDet/base/KVList.cpp:36
#21 0x00007f8b1a4fb59e in KVDetector::~KVDetector (this=0x7456390, __in_chrg=<optimized out>) at /home/frankland/software/sources/kaliveda.git/KVMultiDet/geometry/KVDetector.cpp:210
#22 0x00007f8b00a42859 in KVChIo::~KVChIo (this=0x7456390, __in_chrg=<optimized out>) at /home/frankland/software/sources/kaliveda.git/KVIndra/geometry/KVChIo.cpp:82
#23 0x00007f8b17f4d41f in TList::Delete (this=this
entry=0x6dfad50, option=<optimized out>, option
entry=0x7f8b1bb4337c "") at /home/frankland/software/sources/root/core/cont/src/TList.cxx:534
#24 0x00007f8b17f4679c in THashList::Delete (this=0x6dfad50, option=<optimized out>) at /home/frankland/software/sources/root/core/cont/src/THashList.cxx:215
#25 0x00007f8b18ddb44c in KVSeqCollection::Delete (this=0x6e6bf40, option=0x7f8b1bb4337c "") at /home/frankland/software/sources/kaliveda.git/KVMultiDet/base/KVSeqCollection.cpp:291
#26 0x00007f8b1bb2ff1d in KVMultiDetArray::~KVMultiDetArray (this=0x6e6bee0, __in_chrg=<optimized out>) at /home/frankland/software/sources/kaliveda.git/KVMultiDet/exp_events/KVMultiDetArray.cpp:173
#27 0x00007f8b011117a9 in KVINDRA::~KVINDRA (this=0x6e6bee0, __in_chrg=<optimized out>) at /home/frankland/software/sources/kaliveda.git/KVIndra/exp_events/KVINDRA.cpp:128

**Comment by jdfrankland** [comment]
fixed for 6.14/09
as the problem was a fundamental logic problem in KV, this should work for all versions
